// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.util.Units;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final class DriveConstants {

        public static final double kTrackWidth = Units.inchesToMeters(21);
        
        // Distance between right and left wheels
        public static final double kWheelBase = Units.inchesToMeters(21);
        
        // Distance between front and back wheels
        public static final SwerveDriveKinematics kDriveKinematics = new SwerveDriveKinematics(
                new Translation2d(kWheelBase / 2, kTrackWidth / 2),     //front left
                new Translation2d(kWheelBase / 2, -kTrackWidth / 2),    //front right
                new Translation2d(-kWheelBase / 2, kTrackWidth / 2),    //back left
                new Translation2d(-kWheelBase / 2, -kTrackWidth / 2));  //back right

        public static final int kFrontLeftDriveMotorPort = 16;      //FLD
        public static final int kFrontLeftTurningMotorPort = 11;    //FLT
        public static final int kBackLeftDriveMotorPort = 10;       //BLD
        public static final int kBackLeftTurningMotorPort = 31;     //BLT
        public static final int kFrontRightDriveMotorPort = 15;     //FRD
        public static final int kFrontRightTurningMotorPort = 14;   //FRT
        public static final int kBackRightDriveMotorPort = 30;      //BRD
        public static final int kBackRightTurningMotorPort = 32;    //BRT

        public static final boolean kFrontLeftTurningEncoderReversed = false;
        public static final boolean kBackLeftTurningEncoderReversed = false;
        public static final boolean kFrontRightTurningEncoderReversed = false;
        public static final boolean kBackRightTurningEncoderReversed = false;
        public static final boolean kFrontLeftDriveReversed = false;
        public static final boolean kBackLeftDriveReversed = false;
        public static final boolean kFrontRightDriveReversed = false;
        public static final boolean kBackRightDriveReversed = false;

        //CTR CANcoders
        public static final int kFrontLeftDriveAbsoluteEncoderPort = 20;
        public static final int kBackLeftDriveAbsoluteEncoderPort = 21;
        public static final int kFrontRightDriveAbsoluteEncoderPort = 22;
        public static final int kBackRightDriveAbsoluteEncoderPort = 23;

        public static final boolean kFrontLeftDriveAbsoluteEncoderReversed = false;
        public static final boolean kBackLeftDriveAbsoluteEncoderReversed = false;
        public static final boolean kFrontRightDriveAbsoluteEncoderReversed = false;
        public static final boolean kBackRightDriveAbsoluteEncoderReversed = false;

        public static final double kFrontLeftDriveAbsoluteEncoderOffsetRad = 0.0;
        public static final double kBackLeftDriveAbsoluteEncoderOffsetRad = 0.0;
        public static final double kFrontRightDriveAbsoluteEncoderOffsetRad = 0.0;
        public static final double kBackRightDriveAbsoluteEncoderOffsetRad = 0.0;

        public static final double kPhysicalMaxSpeedMetersPerSecond = 3.81;
        public static final double kPhysicalMaxAngularSpeedRadiansPerSecond = 5 * Math.PI;

        public static final double kTeleDriveMaxSpeedMetersPerSecond = kPhysicalMaxSpeedMetersPerSecond; // 1.5;
        public static final double kTeleDriveMaxAngularSpeedRadiansPerSecond = kPhysicalMaxAngularSpeedRadiansPerSecond / 4;
        public static final double kTeleDriveMaxAccelerationUnitsPerSecond = 2.5;
        public static final double kTeleDriveMaxAngularAccelerationUnitsPerSecond = 2.5;

        public static final double kSlowButtonDriveModifier = 0.25;
        public static final double kSlowButtonTurnModifier = 0.5;
    }

    public final class ModuleConstants{
        public static final double kWheelDiameterMeters = Units.inchesToMeters(3);
        public static final double kDriveMotorGearRatio = 1 / 8.14;
        public static final double kTurningMotorGearRatio = 1 / 12.8;
        public static final double kDriveEncoderRot2Meter = kDriveMotorGearRatio * Math.PI * kWheelDiameterMeters;
        public static final double kTurnEncoderRot2Rad = kTurningMotorGearRatio * 2 * Math.PI;
        public static final double kDriveEncoderRPM2MeterPerSec = kDriveEncoderRot2Meter / 60;
        public static final double kTurnEncoderRPM2RadPerSec = kTurnEncoderRot2Rad / 60;
        public static final double kPTurning = 0.4;
    }

    public final class Sensors {
        public static final int GYRO_ID = 18;
    }

    public final class OIConstants {
        public static final int kDriverControllerPort = 0;
        public static final int kDriverYAxis = 1;
        public static final int kDriverXAxis = 0;
        public static final int kDriverRotAxis = 2;
        public static final int kDriverFieldOrientedButtonIdx = 1;
        public static final double kDeadband = 0.15;
        public static final int fieldOrientedButton = 12;
        public static final int kDriveThrottle = 3;
    }

    public final class ElbowConstants {
        public static final int kDriverControllerPort = 17;
    }

    public final class ElevatorConstants {
        public static final int kDriverControllerPort = 12;        
    }

    public final class GripperConstants {
        public static final int kDriverControllerPort = 13;        
    }
}